services:
  ha-95598:
    env_file:
      - .env
    build:
      context: .
    image: ha-95598
    container_name: ha-95598-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python3", "-m", "scripts.tools.healthcheck"]
      interval: 1m
      timeout: 5s
      retries: 2
      start_period: 2m
    working_dir: /app
    volumes:
      - .:/app
    init: true
